### PR TITLE
fix: hreflang tags is multiliungual sites

### LINKED ISSUE #686: Polylang hreflang links missing
### Describe the bug

The polylang plugin hooks into wp_head to add hreflang links to output references to translated pages. wp_head is a front end hook, therefore needs a different implementation for nextjs app.

### Steps to Reproduce

1. Run headstartwp locally.
2. Make sure Polylang is enabled and languages added. 
3. Create a Page and a translated version.
4. Run FE via WP on localhost:8888 and visit the page. 
5. View source code and check the output of hreflang links exists. 
6. Run the FE on nextjs localhost:3000 and view source code on the same page. 
7. hreflang links are missnig.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lucymtc**
### Description of the Change
Adds a custom Yoast presenter to add hreflangs tags to multilingual site with Polylang.
The logic follows the Polylang plugin's logic to:
- Not Add hreflang tags to paged archives, only to archive on page 1. See: https://wordpress.org/support/topic/hreflang-on-page2
- Follows the recommendations on https://polylang.pro/hreflang-tag-attributes-and-polylang-everything-you-need-to-know to add x-default

Closes https://github.com/10up/headstartwp/issues/686

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: wp/headless-wp/includes/classes/Integrations/PolylangHrefLangs.php [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+				// Get term object for translations and only include hreflang tags if term has posts.
+				$term_obj = $translated_id === $term->term_id ? $term : get_term( $translated_id, $term->taxonomy );
+				if ( 0 === $term_obj->count ) {
+					continue;
+				}
+
+				$hreflangs_urls[ $language ] = get_term_link( $translated_id );
+			}
+		} else {
+			$homepages = $this->get_homepage_post_ids();
```
Comment (lucymtc) [inline wp/headless-wp/includes/classes/Integrations/PolylangHrefLangs.php]: actually this is not needed, missed that Polylang has a setting for this, I'll update

Comment (lucymtc) [reply wp/headless-wp/includes/classes/Integrations/PolylangHrefLangs.php]: fixed the overriding polylang setting for homepage slug

**Review by nicholasio — APPROVED** [review]
