### PR TITLE
fix(plugin.php): updated the Plugin URI to point to the plugin repo

### LINKED ISSUE #519: "Visit plugin site" link is a 404, currently set to false
### Describe the bug

The Vist plugin site link results in a 404, would expect it to take me to the main plugin repo.

### Steps to Reproduce

1. Install the plugin
2. Go to the Plugins page 
3. Click on the "Visit plugin site"
4. Take you to a 404

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bmarshall511**
### Description of the Change

Updated the Plugin URI to point to the plugin repo

Closes #519 

### How to test the Change
1. Go to the plugins page
2. Click the Visit plugin page lint

### Credits
Props @bmarshall511 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: wp/headless-wp/plugin.php [hunk 1]
```diff
@@ -23,13 +23,13 @@
 define( 'HEADLESS_WP_PLUGIN_INC', HEADLESS_WP_PLUGIN_PATH . 'includes/' );
 
 // Load php-jwt classes.
-$jwt_files = [
+$jwt_files = array(
```
Comment (nicholasio) [inline wp/headless-wp/plugin.php]: nit: This change is unrelated, mind rolling this back?

**Review by nicholasio — COMMENTED** [review]
Thanks for catching this.

File: wp/headless-wp/plugin.php (hunk 1 above)
Comment (bmarshall511) [reply wp/headless-wp/plugin.php]: No problem! My IDE updated it automatically on save to conform to WordPress coding standards.

**Review by nicholasio — APPROVED** [review]
