### PR TITLE
fix: post path matching when params.fullPath is set

### LINKED ISSUE #922: Custom post types with fullPath parameter fail to match current path due to incorrect singlePrefix handling
### Describe the bug

When using custom post types with the fullPath parameter, HeadstartWP fails to correctly match posts to the current URL path. This occurs because the core SinglePostFetchStrategy always adds the singlePrefix (custom post type slug) without considering whether a fullPath parameter is provided.
https://github.com/10up/headstartwp/blob/develop/packages/core/src/data/strategies/SinglePostFetchStrategy.ts#L185

This causes path matching to fail when fullPath is provided because:
- The fullPath parameter already contains the complete path including the post type slug.
- Adding the singlePrefix creates an incorrect path comparison.
- Posts never match their actual URLs when fullPath is used.

When params.fullPath is provided, the singlePrefix should be omitted since the full path already contains the correct post type slug.

Example Scenario: Translated Slugs
In a multilingual site, a custom post type "webinars" might have:
- Default language post type slug: /webinars/my-webinar/
- Translated post type slug: /webinare/mein-webinare/ (DE)
When using fullPath with the translated URL, the current logic incorrectly adds /articles/ prefix, making it impossible to match /webinare/mein-webinare/

Setting matchCurrentPath to false is a workaround but still an issue if 2 posts have the same slug for EN and DE 
/webinars/my-webinar/
/webinare/my-webinar/
It will always render the content of the first post in the response.

### Steps to Reproduce

Set up a multilingual WordPress site with custom post type.
Create a custom post type with translated slugs wit Polylang settings
Add fullPath to the request of a single post for the translated post version
Navigate to a translated custom post type URL
Observe that the post is not found, returns 404
Set matchCurrentPath to false and observe the post is found. 

### Screenshots, screen recording, code snippet

_No response_

### Environment information

WP 6.8.2
Polylang Pro 3.6.7
@headstartwp/core 1.5.0-next.8
@headstartwp/next 1.5.0-next.9

### WordPress information

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nicholasio**
### Description of the Change

Closes #922 

### Credits

Props @lucymtc 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: packages/core/src/data/strategies/SinglePostFetchStrategy.ts [hunk 1]
```diff
@@ -182,6 +182,11 @@ export class SinglePostFetchStrategy<
 
 				if (expectedPostTypes.includes(postType)) {
 					const postTypeObject = getCustomPostType(postType, this.baseURL);
+
+					if (params.fullPath) {
+						return postPath === params.fullPath.replace(/\/?$/, '/');
+					}
+
```
Comment (lucymtc) [inline packages/core/src/data/strategies/SinglePostFetchStrategy.ts:193]: This is failing because it doesn't check for the current path with locale like further down  
`postPath === `/${this.locale}${singlePrefix}${currentPath}``

The patch I had:

```
const singlePrefix = params?.fullPath
	? ''
	: (postTypeObject?.single?.replace(/\/?$/, '') ?? '');

return (
    postPath === `${singlePrefix}${currentPath}` ||
    postPath === `/${this.locale}${singlePrefix}${currentPath}`
);
```
As it only needs to have the singlePrefix empty

**Review by lucymtc — CHANGES_REQUESTED** [review]

File: packages/core/src/data/strategies/SinglePostFetchStrategy.ts (hunk 1 above)
Comment (nicholasio) [reply packages/core/src/data/strategies/SinglePostFetchStrategy.ts:193]: updated the logic to also account for locale

**Review by lucymtc — APPROVED** [review]

File: packages/core/src/data/strategies/SinglePostFetchStrategy.ts (hunk 1 above)
Comment (lucymtc) [reply packages/core/src/data/strategies/SinglePostFetchStrategy.ts:193]: thanks! approved @nicholasio
