### PR TITLE
fix: prevent sitemap redirect loop

### LINKED ISSUE #714: Sitemaps that do not exists cause infinite loop
### Describe the bug

By default we rewrite any path that contains sitemap and ends with .xml but when those don't exist in WP it causes a infinite redirect loop

### Steps to Reproduce

From the next.js app visit something like https://localhost:3000/index-sitemap.xml

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nicholasio**
### Description of the Change

Closes #714 

### How to test the Change

- `npm run dev`
- Visit `http://localhost:3000/sitemap.xml` and verify it works fine, as well as any other valid sitemap
- Visit a invalid sitemap e.g: `http://localhost:3000/index-sitemap.xml` and it should redirect to the homepage.

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: wp/headless-wp/includes/classes/Redirect.php [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+
+			// do not redirect for (missing) assets
+			if ( str_starts_with( $url_request, '/wp-content' ) || str_ends_with( $url_request, '.css' ) || str_ends_with( $url_request, '.js' ) ) {
+				return;
+			}
+
+			// if any sitemap requests reaches this point then it is a 404
+			if ( str_contains( $url_request, 'sitemap' ) && str_ends_with( $url_request, '.xml' ) ) {
+				// redirect to the homepage, otherwise users would see a HTTP 404 (not the 404 page on next.js) error on the browser.
+				\wp_redirect( trailingslashit( esc_url_raw( $site_url ) ), 307 );
```
Comment (nicholasio) [inline wp/headless-wp/includes/classes/Redirect.php:62]: I could also set a status header of 404 and exit immediately, that would leep to browser shoing a HTTP 404 error code and not the next.js 404 page... so I opted to just redirect to the homepage.

**Review by tobeycodes — APPROVED** [review]
